### ISSUE TITLE
Deprecation warnings with Ansible 2.4

### ISSUE THREAD

**Issue by szpak** [alertlogic/al-agents-ansible-playbooks#19] opened 2018-03-29 14:22 UTC
Running the playbook with Ansible 2.4(.3.0) the following deprecation warnings are presented:

```
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: win_msi is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

There is a change to have that ansible playbook not compatible with the new Ansible versions.

**Comment by muram** [comment] 2019-02-11 16:31
@szpak I'm not able to reproduce this warning using v2.7.5, can you please confirm what ansible version are you using now and whether this still an issue?

**Comment by szpak** [comment] 2019-02-11 20:57
@muram I'm no longer have access to any Alert Logic instance. I still see `include` in the code in master, so unless the Ansible team hasn't resigned from the deprecation it should still be valid.

@tomaszkiewicz Do you, by any chance, still use Alert Logic?

**Comment by tomaszkiewicz** [comment] 2019-02-12 09:12
@szpak personally I do not use AL, unfortunately corporate policy doesn't allow me to tell you anything more :(

**Comment by muram** [comment] 2019-02-14 18:09
Thanks @szpak and @tomaszkiewicz for the quick response, I will go ahead and close this issue as I'm not able to reproduce with the latest version of ansible. Will re-open this if someone encountered the issue again using the latest version.

**Closed by muram** 2019-02-14 18:09 UTC
